### ISSUE TITLE
Release Micronaut Object Storage 1.0.0

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-object-storage#59]
### Tasks

- [x] Remove snapshots: #95 
- [x] Write documentation: #77 
- [x] Make cloud workflows to only run upon changes on their respective paths: #96 
- [x] ~~Attempt to do all cloud tests in the sync'ed `gradle.yml` workflow by using the optional `setup.sh` step.~~ (not feasible since we need to pass custom secrets)
- [x] Review nullability annotations: #83 #84 #85 #99
- [x] Error handling and logging: #107
